mlflow_project: sft-gsm8k
checkpoint_dir: outputs/sft_gsm8k/checkpoint/
csv_dir: outputs/sft_gsm8k/csv/  # for saving evaluation results

model_path: /Users/hex/workspace2/wingAGI/huggingface_models/Qwen/Qwen3-0.6B
dataset_path: "data/sft/gsm8k"

train_device: cuda:0
eval_device: cuda:1

micro_batch_size: 2
gradient_accumulation_steps: 4
eval_batch_size: 2
num_epochs: 1
learning_rate: 2e-5
weight_decay: 0.01
eval_steps: 1
save_steps: 10


